### ISSUE TITLE
inner_html method not found updating from kitabu 1.0.6 to v2.0.4

### ISSUE THREAD

**Issue by DanielKehoe** [fnando/kitabu#50]
When I updated from kitabu 1.0.6 to v2.0.4, I got the following error (using Ruby 2.0.0):

```
NoMethodError: undefined method `inner_html' for nil:NilClass
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/toc/html.rb:31:in `normalize'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/toc/html.rb:37:in `generate'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter/html.rb:67:in `parse_layout'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter/html.rb:20:in `block in export'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter/html.rb:19:in `open'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter/html.rb:19:in `export'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter/base.rb:13:in `export'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter.rb:32:in `export!'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter.rb:5:in `run'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/cli.rb:38:in `export'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/bin/kitabu:5:in `<top (required)>'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/bin/kitabu:23:in `load'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/bin/kitabu:23:in `<main>'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/bin/ruby_executable_hooks:15:in `eval'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/bin/ruby_executable_hooks:15:in `<main>'
/Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter/pdf.rb:17:in `create_html_file': undefined method `set_attribute' for nil:NilClass (NoMethodError)
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter/pdf.rb:12:in `apply_footnotes!'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter/pdf.rb:5:in `export'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter/base.rb:13:in `export'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter.rb:33:in `export!'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/exporter.rb:5:in `run'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/lib/kitabu/cli.rb:38:in `export'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/gems/kitabu-2.0.4/bin/kitabu:5:in `<top (required)>'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/bin/kitabu:23:in `load'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/bin/kitabu:23:in `<main>'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/bin/ruby_executable_hooks:15:in `eval'
    from /Users/danielkehoe/.rvm/gems/ruby-2.0.0-p643@tutorials/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fnando** [comment]
I'm sorry for taking 7 years to answer this. You probably won't even remember what happened, so I'm going to close this ticket. Let me know if you face the same issue ever again with whatever code is on HEAD, and I promise I'l take a few years off the reply eta. 😬
